version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1
  opsgenie: opsgenie/opsgenie@1.0.8

jobs:
  frontend-code-test:
    resource_class: large
    docker:
      - image: cimg/node:16.20
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - yarn-deps-{{ checksum "frontend/yarn.lock" }}
      - run:
          name: Install node dependencies
          command: |
            yarn --version
            cd ${CIRCLE_WORKING_DIRECTORY}/frontend
            yarn install
      - save_cache:
          key: yarn-deps-{{ checksum "frontend/yarn.lock" }}
          paths:
            - frontend/node_modules
            - env
      - run:
          name: Run yarn test
          command: |
            cd ${CIRCLE_WORKING_DIRECTORY}/frontend/
            CI=true yarn test -w 1
            CI=true GENERATE_SOURCEMAP=false yarn build

  backend-code-check-PEP8:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: flake8 tests
          command: | 
            pip install flake8
            flake8 manage.py backend tests migrations

  backend-code-check-Black:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: black tests
          command: | 
            pip install black
            black --check manage.py backend tests migrations

  backend-functional-tests:
    resource_class: large
    docker:
      - image: cimg/python:3.9
        environment:
          SQLALCHEMY_DATABASE_URI: postgresql://taskingmanager@localhost/test_tm
      - image: cimg/postgres:14.2-postgis
        environment:
          POSTGRES_USER: taskingmanager
          POSTGRES_DB: test_tm
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install packages
          command: |
            sudo apt-get update
            sudo apt-get install -y libgeos-dev # Required for shapely
      - run:
          name: Configure Postgresql Test database
          command: |
            sudo apt-get install postgresql-client
            psql -h localhost -U $POSTGRES_USER test_$POSTGRES_DB -c "CREATE EXTENSION postgis;"
      - run:
          name: Run backend functional tests
          command: |
            mkdir ${CIRCLE_WORKING_DIRECTORY}/tests/backend/results
            find ./tests/backend -name "test*.py" -exec chmod -x {} \;
            nosetests ./tests/backend --with-xunit \
              --xunit-file ${CIRCLE_WORKING_DIRECTORY}/tests/backend/results/unitresults.xml \
              --with-coverage --cover-erase --cover-package=./backend
            coverage xml -o ${CIRCLE_WORKING_DIRECTORY}/tests/backend/results/coverage.xml
      - store_test_results:
          path: tests/backend/results/unitresults.xml
      - store_artifacts:
          path: tests/backend/results

  database-backup:
    resource_class: large
    parameters:
      stack_name:
        description: "Cloudformation stack name"
        type: string
    docker:
      - image: cimg/postgres:15.1-postgis
    steps:
      - setup_remote_docker
      - aws-cli/setup:
          role-arn: "arn:aws:iam::$ORG_AWS_ACCOUNT_ID:role/CircleCI-OIDC-Connect"
          profile-name: "OIDC-Profile"
          role-session-name: "database-snapshot"
          session-duration: "2700"
      - run:
          name: Find the instance ID of the database in the stack to backup
          command: |
            RDS_ID=$(aws rds describe-db-instances --query 'DBInstances[?contains(TagList[].Key, `aws:cloudformation:stack-name`) && contains(Taglist[].Value, `tasking-manager-<< parameters.stack_name >>`)].[DBInstanceIdentifier]' --output text)
            echo "export RDS_ID=$RDS_ID" >> $BASH_ENV
      - run:
          name: Find Snapshot creation timestamp
          command: |
            # Given instance ID, find the timestamp of the latest snapshot
            SNAPSHOT_TIMESTAMP=$(aws rds describe-db-snapshots \
              --db-instance-identifier=${RDS_ID} \
              --query="max_by(DBSnapshots, &SnapshotCreateTime).OriginalSnapshotCreateTime" \
              --output text)
      - run:
          name: Make Database Backup
          no_output_timeout: 15m
          command: |
            aws rds wait db-instance-available \
                --db-instance-identifier ${RDS_ID}
            # create new aws rds snapshot
            aws rds create-db-snapshot \
                --db-snapshot-identifier tm4-<< parameters.stack_name >>-${RDS_ID}-$(date -I) \
                --db-instance-identifier ${RDS_ID}
            aws rds wait db-snapshot-completed \
                --db-snapshot-identifier tm4-<< parameters.stack_name >>-${RDS_ID}-$(date -I) \
                --db-instance-identifier ${RDS_ID}
            if [[ $? -eq 255 ]]; then
              echo "Production snapshot creation failed. Exiting with exit-code 125"
              exit 125
            fi
            something here
      - run:
          name: Check / validate backup
          command: |
            echo "something here"

  build:
    working_directory: /home/circleci/app
    docker:
      - image: cimg/python:3.7.14-node
        environment:
          SQLALCHEMY_DATABASE_URI: postgresql://taskingmanager@localhost/test_tm
      - image: cimg/postgres:14.2-postgis
        environment:
          POSTGRES_USER: taskingmanager
          POSTGRES_DB: test_tm
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install modules
          command: |
            sudo apt-get update
            sudo apt-get install -y libgeos-dev # Required for shapely
      - run:
          name: Configure Postgresql Test database
          command: |
            sudo apt-get install postgresql-client
            psql -h localhost -U $POSTGRES_USER test_$POSTGRES_DB -c "CREATE EXTENSION postgis;"
      - run:
          name: Set folder permissions
          command: |
            chown -R circleci:circleci ${CIRCLE_WORKING_DIRECTORY}
            chmod -R 755 ${CIRCLE_WORKING_DIRECTORY}
      - restore_cache:
          keys:
            - node-{{ .Environment.CACHEVERSION }}-{{ .Branch }}-{{ checksum "frontend/yarn.lock" }}
      - run:
          name: Install requirements
          command: |
            # Install NPM packages and build frontend
            cd ${CIRCLE_WORKING_DIRECTORY}/frontend
            yarn
            cd ${CIRCLE_WORKING_DIRECTORY}
            # Install Python dependencies
            pip install --upgrade pip pdm
            pdm config --global python.use_venv False
            pdm export --prod --without-hashes > requirements.txt
            pip install -r requirements.txt
      - run:
          name: Run backend tests
          command: |
            # Run Python tests
            cd ${CIRCLE_WORKING_DIRECTORY}
            mkdir ${CIRCLE_WORKING_DIRECTORY}/tests/backend/results
            find ./tests/backend -name "test*.py" -exec chmod -x {} \;
            nosetests ./tests/backend --with-xunit \
              --xunit-file ${CIRCLE_WORKING_DIRECTORY}/tests/backend/results/unitresults.xml \
              --with-coverage --cover-erase --cover-package=./backend
            coverage xml -o ${CIRCLE_WORKING_DIRECTORY}/tests/backend/results/coverage.xml
      - store_test_results:
          path: tests/backend/results/unitresults.xml
      - store_artifacts:
          path: tests/backend/results
      - save_cache:
          key: node-{{ .Environment.CACHEVERSION }}-{{ .Branch }}-{{ checksum "frontend/yarn.lock" }}
          paths:
            - frontend/node_modules
            - env
    # The resource_class feature allows configuring CPU and RAM resources for each job. Different resource classes are available for different executors. https://circleci.com/docs/2.0/configuration-reference/#resourceclass
    resource_class: large

  backend_deploy:
    parameters:
      stack_name:
        description: "the name of the stack for cfn-config"
        type: string
      gitsha:
        description: "The 40 char hash of the git commit"
        type: string
    working_directory: /home/circleci/tasking-manager
    resource_class: medium
    docker:
      - image: cimg/python:3.7.14-node
    steps:
      - checkout
      - setup_remote_docker
      - aws-cli/setup:
          role-arn: "arn:aws:iam::$ORG_AWS_ACCOUNT_ID:role/CircleCI-OIDC-Connect"
          profile-name: "OIDC-Profile"
          role-session-name: "backend-deploy"
          session-duration: "2700"
      - run:
          name: Install modules
          command: |
            sudo apt-get update
            sudo apt-get install -y libgeos-dev jq # Required for shapely
            sudo yarn global add @mapbox/cfn-config @mapbox/cloudfriend

      - run:
          name: Download config file
          command: |
            export GITSHA=<< parameters.gitsha >>
            aws s3 cp s3://hot-cfn-config/tasking-manager/tasking-manager-<< parameters.stack_name >>-${AWS_REGION}.cfn.json - | jq -c --arg GITSHA "$GITSHA" '.GitSha = $GITSHA' > $CIRCLE_WORKING_DIRECTORY/cfn-config-<< parameters.stack_name >>.json
      - deploy:
          name: Deploy to << parameters.stack_name >>
          command: |
            export NODE_PATH=/usr/local/share/.config/yarn/global/node_modules/
            validate-template $CIRCLE_WORKING_DIRECTORY/scripts/aws/cloudformation/tasking-manager.template.js
            export JSON_CONFIG="$(cat $CIRCLE_WORKING_DIRECTORY/cfn-config-<< parameters.stack_name >>.json)"
            cfn-config update << parameters.stack_name >> $CIRCLE_WORKING_DIRECTORY/scripts/aws/cloudformation/tasking-manager.template.js -f -c hot-cfn-config -t hot-cfn-config -r $AWS_REGION -p "$JSON_CONFIG"

  frontend_deploy:
    working_directory: /home/circleci/tasking-manager
    resource_class: large
    docker:
      - image: cimg/python:3.7.14-node
    parameters:
      stack_name:
        description: "the name of the stack for cfn-config"
        type: string
    steps:
      - checkout
      - setup_remote_docker
      - aws-cli/setup:
          role-arn: "arn:aws:iam::$ORG_AWS_ACCOUNT_ID:role/CircleCI-OIDC-Connect"
          profile-name: "OIDC-Profile"
          role-session-name: "frontend-deploy"
          session-duration: "1800"
      - run:
          name: Deploy Frontend to S3
          command: |
            cd ${CIRCLE_WORKING_DIRECTORY}/frontend/
            export TM_ENVIRONMENT=<< parameters.stack_name >>
            yarn
            CI=true GENERATE_SOURCEMAP=false yarn build
            aws s3 sync build/ s3://tasking-manager-<< parameters.stack_name >>-react-app --delete --cache-control max-age=31536000
            aws s3 cp s3://tasking-manager-<< parameters.stack_name >>-react-app s3://tasking-manager-<< parameters.stack_name >>-react-app --recursive --exclude "*" --include "*.html" --metadata-directive REPLACE --cache-control no-cache --content-type text/html
            export DISTRIBUTION_ID=`aws cloudformation list-exports --output=text --query "Exports[?Name=='tasking-manager-<< parameters.stack_name >>-cloudfront-id-${AWS_REGION}'].Value"`
            aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"

workflows:
  version: 2

  production-all:
    when:
      and:
        - equal: [ deployment/hot-tasking-manager, << pipeline.git.branch >> ]
    jobs:
      - database-backup:
          name: Backup production database
          stack_name: "tm4-production"
          context:
            - org-global
            - tasking-manager-tm4-production
      - backend-functional-tests
      - backend_deploy:
          name: backend-production
          stack_name: "tm4-production"
          requires:
            - backend-functional-tests
            - database-backup
          gitsha: $CIRCLE_SHA1
          context:
            - org-global
            - tasking-manager-tm4-production
      - frontend_deploy:
          name: frontend-production
          stack_name: "tm4-production"
          requires:
            - backend-functional-tests
          context:
            - org-global
            - tasking-manager-tm4-production

  production-frontend-only:
    when:
      and:
        - equal: [ deployment/hot-tasking-manager-frontend, << pipeline.git.branch >> ]
    jobs:
      - backend-functional-tests
      - frontend_deploy:
          stack_name: "tm4-production"
          context:
            - org-global
            - tasking-manager-tm4-production

  production-backend-only:
    when:
      and:
        - equal: [ deployment/hot-tasking-manager-backend, << pipeline.git.branch >> ]
    jobs:
      - backend_deploy:
          name: backend-production
          stack_name: "tm4-production"
          gitsha: $CIRCLE_SHA1
          context:
            - org-global
            - tasking-manager-tm4-production

  teachosm-all:
    when:
      and:
        - equal: [ deployment/teachosm-tasking-manager, << pipeline.git.branch >> ]
    jobs:
      - database-backup:
          name: Backup TeachOSM database
          stack_name: "teachosm"
          context:
            - org-global
            - tasking-manager-teachosm
      - backend-functional-tests
      - backend_deploy:
          name: Deploy TeachOSM Backend
          stack_name: "teachosm"
          requires:
            - backend-functional-tests
          gitsha: $CIRCLECI_SHA1
          context: tasking-manager-teachosm
      - frontend_deploy:
          name: Deploy TeachOSM Frontend
          stack_name: "teachosm"
          requires:
            - backend-functional-tests
          context: tasking-manager-teachosm

  tm-assisted-all:
    when:
      and:
        - equal: [ deployment/assisted-tasking-manager, << pipeline.git.branch >> ]
    jobs:
      - database-backup:
          name: Backup TM Assisted database
          stack_name: "assisted"
          context:
            - org-global
            - tasking-manager-assisted
      - backend-functional-tests
      - backend_deploy:
          name: Deploy TM Assisted Backend
          stack_name: "assisted"
          requires:
            - backend-functional-tests
          gitsha: $CIRCLECI_SHA1
          context: tasking-manager-assisted
      - frontend_deploy:
          name: Deploy TM Assisted Frontend
          stack_name: "assisted"
          requires:
            - backend-functional-tests
          context: tasking-manager-assisted

  development-staging-all:
    when:
      and:
        - not:
          matches:
            pattern: "^deployment/.*"
            value: << pipeline.git.branch >>
        - or:
          - equal: [ develop, << pipeline.git.branch >> ]
          - equal: [ staging-test, << pipeline.git.branch >> ]
    jobs:
      - database-backup:
          name: Backup staging database
          stack_name: "staging"
          context:
            - org-global
            - tasking-manager-staging
      - frontend-code-test
      - backend-code-check-PEP8
      - backend-code-check-Black
      - backend-functional-tests
      - backend_deploy:
          name: Deploy development/staging backend
          gitsha: $CIRCLE_SHA1
          stack_name: "staging"
          requires:
            - backend-code-check-PEP8
            - backend-code-check-Black
            - backend-functional-tests
          context:
            - org-global
            - tasking-manager-staging
      - frontend_deploy:
          name: Deploy development/staging frontend
          stack_name: "staging"
          requires:
            - frontend-code-test
          context:
            - org-global
            - tasking-manager-staging

  build-only-all:
    when:
      not:
        matches:
          pattern: "^deployment/.*"
          value: << pipeline.git.branch >>
    jobs:
      - frontend-code-test
      - backend-code-check-PEP8
      - backend-code-check-Black
      - backend-functional-tests

  the-modern-flow:
    when:
      or:
        - equal: [ enhance/terraform-container-infrastructure, << pipeline.git.branch >> ]
        - equal: [ enhance/circleci-syntactic-sugar, << pipeline.git.branch >> ]
    jobs:
      - frontend-code-test:
          context:
            - org-global
            - tasking-manager-frontend

      - backend-code-check-PEP8:
          context:
            - org-global
            - tasking-manager-frontend

      - backend-code-check-Black:
          context:
            - org-global
            - tasking-manager-frontend

      - backend-functional-tests:
          context:
            - org-global
            - tasking-manager-frontend
          requires:
            - backend-code-check-PEP8
            - backend-code-check-Black

notify:
  webhooks:
    - url: https://api.opsgenie.com/v1/json/circleci?apiKey=${OPSGENIE_API}

