version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1
  opsgenie: opsgenie/opsgenie@1.0.8

jobs:
  frontend-code-test:
    resource_class: large
    docker:
      - image: cimg/node:16.20
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - yarn-deps-{{ checksum "frontend/yarn.lock" }}
      - run:
          name: Install node dependencies
          command: |
            yarn --version
            cd ${CIRCLE_WORKING_DIRECTORY}/frontend
            yarn install
      - save_cache:
          key: yarn-deps-{{ checksum "frontend/yarn.lock" }}
          paths:
            - frontend/node_modules
            - env
      - run:
          name: Run yarn test
          command: |
            cd ${CIRCLE_WORKING_DIRECTORY}/frontend/
            CI=true yarn test -w 1
            CI=true GENERATE_SOURCEMAP=false yarn build

  backend-code-check-PEP8:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: flake8 tests
          command: | 
            pip install flake8
            flake8 manage.py backend tests migrations

  backend-code-check-Black:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: black tests
          command: | 
            pip install black
            black --check manage.py backend tests migrations

  backend-functional-tests:
    resource_class: large
    docker:

      - image: cimg/python:3.9
        environment:
          SQLALCHEMY_DATABASE_URI: postgresql://taskingmanager@localhost/test_tm
          POSTGRES_TEST_DB: test_tm
          POSTGRES_USER: taskingmanager
          POSTGRES_ENDPOINT: localhost

      - image: cimg/postgres:14.2-postgis
        environment:
          POSTGRES_USER: taskingmanager
          POSTGRES_DB: test_tm

    steps:
      - checkout
      - setup_remote_docker
      - run: sudo apt-get update
      - run: sudo apt-get -y install libgeos-dev # Required for shapely
      - run: sudo apt-get -y install proj-bin libproj-dev
      - run:
          name: Configure Postgresql Test database
          command: |
            psql \
            -d $SQLALCHEMY_DATABASE_URI \
            -c "CREATE EXTENSION postgis;"
      - run: pip install --upgrade pip pdm
      - run: pdm config --global python.use_venv False
      - run: pdm export --prod --without-hashes > requirements.txt
      - run: pip install -r requirements.txt
      - run: mkdir --mode 766 -p /tmp/logs
      - run: mkdir ${CIRCLE_WORKING_DIRECTORY}/tests/backend/results
      - run: find ./tests/backend -name "test*.py" -exec chmod -x {} \;
      - run: echo "export TM_LOG_DIR=/tmp/logs" >> $BASH_ENV
      - run:
          name: Run backend functional tests
          command: |
            nosetests ./tests/backend --with-xunit \
              --xunit-file ${CIRCLE_WORKING_DIRECTORY}/tests/backend/results/unitresults.xml \
              --with-coverage --cover-erase --cover-package=./backend
      - run: coverage xml -o ${CIRCLE_WORKING_DIRECTORY}/tests/backend/results/coverage.xml
      - store_test_results:
          path: tests/backend/results/unitresults.xml
      - store_artifacts:
          path: tests/backend/results

  database-backup:
    resource_class: large
    parameters:
      stack_name:
        description: "Cloudformation stack name"
        type: string
    docker:
      - image: cimg/postgres:15.1-postgis
    steps:
      - setup_remote_docker
      - aws-cli/setup:
          role-arn: "arn:aws:iam::$ORG_AWS_ACCOUNT_ID:role/CircleCI-OIDC-Connect"
          profile-name: "OIDC-Profile"
          role-session-name: "database-snapshot"
          session-duration: "2700"
      - run:
          name: Find the instance ID of the database in the stack to backup
          command: |
            RDS_ID=$(aws rds describe-db-instances \
              --query 'DBInstances[?contains(TagList[].Key, `aws:cloudformation:stack-name`) && contains(TagList[].Value, `tasking-manager-<< parameters.stack_name >>`)].[DBInstanceIdentifier]' \
              --output text)
            echo "export RDS_ID=$RDS_ID" >> $BASH_ENV
      - run:
          name: Find Snapshot creation timestamp
          command: |
            # Given instance ID, find the timestamp of the latest snapshot
            SNAPSHOT_TIMESTAMP=$(aws rds describe-db-snapshots \
              --db-instance-identifier=${RDS_ID} \
              --query="max_by(DBSnapshots, &SnapshotCreateTime).OriginalSnapshotCreateTime" \
              --output text)
      - run:
          name: Make Database Backup
          no_output_timeout: 15m
          command: |
            aws rds wait db-instance-available \
                --db-instance-identifier ${RDS_ID}
            # create new aws rds snapshot
            printf -v time_now '%(%Y-%m-%d-%H-%M)T' -1
            aws rds create-db-snapshot \
                --db-snapshot-identifier tm4-<< parameters.stack_name >>-${RDS_ID}-${time_now} \
                --db-instance-identifier ${RDS_ID}
            aws rds wait db-snapshot-completed \
                --db-snapshot-identifier tm4-<< parameters.stack_name >>-${RDS_ID}-${time_now} \
                --db-instance-identifier ${RDS_ID}
            if [[ $? -eq 255 ]]; then
              echo "Production snapshot creation failed. Exiting with exit-code 125"
              exit 125
            fi
      - run:
          name: Check / validate backup
          command: |
            echo "TODO: BACKUP VALIDATION NOT IMPLEMENTED"

  build:
    working_directory: /home/circleci/app
    docker:
      - image: cimg/python:3.9.14-node
        environment:
          SQLALCHEMY_DATABASE_URI: postgresql://taskingmanager@localhost/test_tm
      - image: cimg/postgres:14.2-postgis
        environment:
          POSTGRES_USER: taskingmanager
          POSTGRES_DB: test_tm
    steps:
      - checkout
      - setup_remote_docker
      - run: sudo apt-get -y update
      - run: sudo apt-get -y install libgeos-dev # Required for shapely
      - run: sudo apt-get install postgresql-client
      - run: psql -h localhost -U $POSTGRES_USER test_$POSTGRES_DB -c "CREATE EXTENSION postgis;"
      - run: chown -R circleci:circleci ${CIRCLE_WORKING_DIRECTORY}
      - run: chmod -R 755 ${CIRCLE_WORKING_DIRECTORY}
      - restore_cache:
          keys:
            - node-{{ .Environment.CACHEVERSION }}-{{ .Branch }}-{{ checksum "frontend/yarn.lock" }}
      - run: cd ${CIRCLE_WORKING_DIRECTORY}/frontend && yarn 
      - run: cd ${CIRCLE_WORKING_DIRECTORY}
      - run: pip install --upgrade pip pdm
      - run: pdm config --global python.use_venv False
      - run: pdm export --prod --without-hashes > requirements.txt
      - run: pip install -r requirements.txt
      - run: mkdir ${CIRCLE_WORKING_DIRECTORY}/tests/backend/results
      - run: find ./tests/backend -name "test*.py" -exec chmod -x {} \;
      - run: coverage erase
      - run:
          name: Run backend tests
          command: |
            nosetests ./tests/backend --with-xunit \
              --xunit-file ${CIRCLE_WORKING_DIRECTORY}/tests/backend/results/unitresults.xml \
              --with-coverage --cover-erase --cover-package=./backend
      - run: coverage xml -o ${CIRCLE_WORKING_DIRECTORY}/tests/backend/results/coverage.xml
      - store_test_results:
          path: tests/backend/results/unitresults.xml
      - store_artifacts:
          path: tests/backend/results
      - save_cache:
          key: node-{{ .Environment.CACHEVERSION }}-{{ .Branch }}-{{ checksum "frontend/yarn.lock" }}
          paths:
            - frontend/node_modules
            - env
    # https://circleci.com/docs/2.0/configuration-reference/#resourceclass
    resource_class: large

  backend_deploy:
    parameters:
      stack_name:
        description: "the name of the stack for cfn-config"
        type: string
      gitsha:
        description: "The 40 char hash of the git commit"
        type: string
      host_ami:
        description: "AMI of the host instance"
        type: string
      pg_version:
        description: "Engine version of PostgreSQL database"
        type: string
        default: "11.19"
      pg_param_group:
        description: "Parameter group for RDS PostgreSQL server"
        type: string
        default: "tm3-logging-postgres11"
      db_instance_type:
        description: "RDS DB Instance class for the backend database"
        type: string
        default: "db.t3.xlarge"
    working_directory: /home/circleci/tasking-manager
    resource_class: medium
    docker:
      - image: cimg/python:3.9.14-node
    steps:
      - checkout
      - setup_remote_docker
      - aws-cli/setup:
          role-arn: "arn:aws:iam::$ORG_AWS_ACCOUNT_ID:role/CircleCI-OIDC-Connect"
          profile-name: "OIDC-Profile"
          role-session-name: "backend-deploy"
          session-duration: "2700"
      - run: sudo apt-get update
      - run: sudo apt-get -y install libgeos-dev jq
      - run: sudo yarn global add @mapbox/cfn-config @mapbox/cloudfriend
      - run:
          name: Download and patch Cloudformation parameter JSON file
          command: |
            tmpfile=$(mktemp)
            aws s3 cp s3://hot-cfn-config/tasking-manager/tasking-manager-<< parameters.stack_name >>-${AWS_REGION}.cfn.json /tmp/tasking-manager.cfn.json
            jq --compact-output \
              --arg GITSHA "<< parameters.gitsha >>" \
              --arg AMI "<< parameters.host_ami >>" \
              --arg PGVERSION "<< parameters.pg_version >>" \
              --arg DBTYPE "<< parameters.db_instance_type >>" \
              '.GitSha = $GITSHA | .TaskingManagerBackendAMI = $AMI | .DatabaseEngineVersion = $PGVERSION | .DatabaseInstanceType = $DBTYPE' \
              /tmp/tasking-manager.cfn.json > "$tmpfile" && mv "$tmpfile" $CIRCLE_WORKING_DIRECTORY/cfn-config-<< parameters.stack_name >>.json
      - deploy:
          name: Deploy to << parameters.stack_name >>
          command: |
            export NODE_PATH=/usr/local/share/.config/yarn/global/node_modules/
            validate-template $CIRCLE_WORKING_DIRECTORY/scripts/aws/cloudformation/tasking-manager.template.js
            export JSON_CONFIG="$(< $CIRCLE_WORKING_DIRECTORY/cfn-config-<< parameters.stack_name >>.json)"
            cfn-config update << parameters.stack_name >> $CIRCLE_WORKING_DIRECTORY/scripts/aws/cloudformation/tasking-manager.template.js -f -c hot-cfn-config -t hot-cfn-config -r $AWS_REGION -p "$JSON_CONFIG"

  frontend_deploy:
    working_directory: /home/circleci/tasking-manager
    resource_class: large
    docker:
      - image: cimg/python:3.9.14-node
    parameters:
      stack_name:
        description: "the name of the stack for cfn-config"
        type: string
    steps:
      - checkout
      - setup_remote_docker
      - aws-cli/setup:
          role-arn: "arn:aws:iam::$ORG_AWS_ACCOUNT_ID:role/CircleCI-OIDC-Connect"
          profile-name: "OIDC-Profile"
          role-session-name: "frontend-deploy"
          session-duration: "1800"
      - run:
          name: Deploy Frontend to S3
          command: |
            cd ${CIRCLE_WORKING_DIRECTORY}/frontend/
            export TM_ENVIRONMENT=<< parameters.stack_name >>
            yarn
            CI=true GENERATE_SOURCEMAP=false yarn build
            aws s3 sync build/ s3://tasking-manager-<< parameters.stack_name >>-react-app --delete --cache-control max-age=31536000
            aws s3 cp s3://tasking-manager-<< parameters.stack_name >>-react-app s3://tasking-manager-<< parameters.stack_name >>-react-app --recursive --exclude "*" --include "*.html" --metadata-directive REPLACE --cache-control no-cache --content-type text/html
            export DISTRIBUTION_ID=`aws cloudformation list-exports --output=text --query "Exports[?Name=='tasking-manager-<< parameters.stack_name >>-cloudfront-id-${AWS_REGION}'].Value"`
            aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"

workflows:
  version: 2

  production-all:
    when:
      and:
        - equal: [ deployment/hot-tasking-manager, << pipeline.git.branch >> ]
    jobs:
      - database-backup:
          name: Backup production database
          stack_name: "tm4-production"
          context:
            - org-global
            - tasking-manager-tm4-production
      - backend-functional-tests
      - backend_deploy:
          name: backend-production
          gitsha: $CIRCLE_SHA1
          stack_name: "tm4-production"
          host_ami: "ami-0aa2b7722dc1b5612"
          requires:
            - backend-functional-tests
            - database-backup
          context:
            - org-global
            - tasking-manager-tm4-production
      - frontend_deploy:
          name: frontend-production
          stack_name: "tm4-production"
          requires:
            - backend-functional-tests
          context:
            - org-global
            - tasking-manager-tm4-production

  production-frontend-only:
    when:
      and:
        - equal: [ deployment/hot-tasking-manager-frontend, << pipeline.git.branch >> ]
    jobs:
      - backend-functional-tests
      - frontend_deploy:
          stack_name: "tm4-production"
          context:
            - org-global
            - tasking-manager-tm4-production

  production-backend-only:
    when:
      and:
        - equal: [ deployment/hot-tasking-manager-backend, << pipeline.git.branch >> ]
    jobs:
      - backend_deploy:
          name: backend-production
          gitsha: $CIRCLE_SHA1
          stack_name: "tm4-production"
          host_ami: "ami-0aa2b7722dc1b5612"
          context:
            - org-global
            - tasking-manager-tm4-production

  teachosm-all:
    when:
      and:
        - equal: [ deployment/teachosm-tasking-manager, << pipeline.git.branch >> ]
    jobs:
      - database-backup:
          name: Backup TeachOSM database
          stack_name: "teachosm"
          context:
            - org-global
            - tasking-manager-teachosm
      - backend-functional-tests
      - backend_deploy:
          name: Deploy TeachOSM Backend
          gitsha: $CIRCLECI_SHA1
          stack_name: "teachosm"
          host_ami: "ami-0aa2b7722dc1b5612"
          requires:
            - backend-functional-tests
          context: tasking-manager-teachosm
      - frontend_deploy:
          name: Deploy TeachOSM Frontend
          stack_name: "teachosm"
          requires:
            - backend-functional-tests
          context: tasking-manager-teachosm

  tm-assisted-all:
    when:
      and:
        - equal: [ deployment/assisted-tasking-manager, << pipeline.git.branch >> ]
    jobs:
      - database-backup:
          name: Backup TM Assisted database
          stack_name: "assisted"
          context:
            - org-global
            - tasking-manager-assisted
      - backend-functional-tests
      - backend_deploy:
          name: Deploy TM Assisted Backend
          gitsha: $CIRCLECI_SHA1
          stack_name: "assisted"
          host_ami: "ami-0aa2b7722dc1b5612"
          requires:
            - backend-functional-tests
          context: tasking-manager-assisted
      - frontend_deploy:
          name: Deploy TM Assisted Frontend
          stack_name: "assisted"
          requires:
            - backend-functional-tests
          context: tasking-manager-assisted

  development-staging-all:
    when:
      and:
        - not:
          matches:
            pattern: "^deployment/.*"
            value: << pipeline.git.branch >>
        - or:
          - equal: [ develop, << pipeline.git.branch >> ]
          - equal: [ staging-test, << pipeline.git.branch >> ]
    jobs:
      - database-backup:
          name: Backup staging database
          stack_name: "staging"
          context:
            - org-global
            - tasking-manager-staging
      - frontend-code-test
      - backend-code-check-PEP8
      - backend-code-check-Black
      - backend-functional-tests
      - backend_deploy:
          name: Deploy development/staging backend
          gitsha: $CIRCLE_SHA1
          stack_name: "staging"
          host_ami: "ami-0fec2c2e2017f4e7b"
          pg_version: "13.10"
          pg_param_group: "default.postgres13"
          db_instance_type: "db.t4g.small"
          requires:
            - backend-code-check-PEP8
            - backend-code-check-Black
            - backend-functional-tests
          context:
            - org-global
            - tasking-manager-staging
      - frontend_deploy:
          name: Deploy development/staging frontend
          stack_name: "staging"
          requires:
            - frontend-code-test
          context:
            - org-global
            - tasking-manager-staging

  build-only-all:
    when:
      not:
        matches:
          pattern: "^deployment/.*"
          value: << pipeline.git.branch >>
    jobs:
      - frontend-code-test
      - backend-code-check-PEP8
      - backend-code-check-Black
      - backend-functional-tests

notify:
  webhooks:
    - url: https://api.opsgenie.com/v1/json/circleci?apiKey=${OPSGENIE_API}

